title: The Magic Pennies - EPK
description: Electronic Press Kit for The Magic Pennies
baseurl: "/music"
url: "https://matthewbierrum.github.io"

theme: minima

# Build settings
markdown: kramdown
permalink: pretty

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
